### ISSUE TITLE
[ISSUE] Output bad channel configuration

### ISSUE THREAD

**Issue by xamix** [JasperG/TalkieWalkie#1]
Hello,

In file Output.java it seem that the bufferSize can be wrong because of wrong use of Configuration.AUDIO_CHANNEL_IN:

`final int bufferSize = AudioTrack.getMinBufferSize(Configuration.AUDIO_SAMPLERATE, Configuration.AUDIO_CHANNEL_IN, Configuration.AUDIO_FORMAT);`

FIX with:

`final int bufferSize = AudioTrack.getMinBufferSize(Configuration.AUDIO_SAMPLERATE, Configuration.AUDIO_CHANNEL_OUT, Configuration.AUDIO_FORMAT);`

**Comment by JasperG** [comment]
Thank you for your comment.
I have noticed that, apparently. I have just committed my changes since.
If you find anything else, please do not hesitate to let me know. Thanks!

**Comment by xamix** [comment]
For sure I will let you know about other issue.
