### ISSUE TITLE
[ISSUE] Android permission audio record not granted at runtime with  API 23 or greater

### ISSUE THREAD

**Issue by xamix** [JasperG/TalkieWalkie#2]
Hello,

If you run with android 6 or later you have to ask for the RECORD_AUDIO permission at runtime.
Otherwise Input fail when create AudioRecord.

FIX:
```

if(android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M)
            requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO}, 0);
```

**Comment by JasperG** [comment]
This is not necessary if you set targetSdkVersion to 22. See _build.gradle_

**Comment by xamix** [comment]
Ha yes I work with latest buildtools.
Thats why I need that.

**Comment by JasperG** [comment]
👍 Well, even with the latest tools (which, I also use), you should be able to set the targetSdkVersion to 22, and thereby completely eliminating the problem.
Obviously, a walkie-talkie app is useless if the user is given a chance to disable the mic completely :)

**Comment by xamix** [comment]
Yes I fully understand.
I'm used to target the latest platform.
